# Generated by Django 3.0.14 on 2021-10-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40, null=True)),
                ('file', models.FileField(upload_to='uploads/', verbose_name='첨부 파일')),
            ],
        ),
    ]
