# Generated by Django 3.0.14 on 2021-10-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_auto_20211010_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
