# Generated by Django 3.0.14 on 2021-10-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0007_auto_20211011_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(upload_to='salary/'),
        ),
    ]
