# Generated by Django 3.0.14 on 2021-10-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0009_employeelist_salarycalculate_salarysum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeelist',
            old_name='uploadFile',
            new_name='uploadedFile',
        ),
        migrations.RenameField(
            model_name='salarycalculate',
            old_name='uploadFile',
            new_name='uploadedFile',
        ),
        migrations.RenameField(
            model_name='salarysum',
            old_name='uploadFile',
            new_name='uploadedFile',
        ),
    ]
