# Generated by Django 3.0.14 on 2021-10-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0010_auto_20211013_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceltestdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('ssnum', models.CharField(max_length=300)),
                ('onemonth', models.IntegerField()),
                ('twomonth', models.IntegerField()),
                ('thmonth', models.IntegerField()),
            ],
        ),
    ]
