# Generated by Django 3.0.14 on 2021-10-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0011_exceltestdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceltestdata',
            name='code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exceltestdata',
            name='onemonth',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exceltestdata',
            name='thmonth',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exceltestdata',
            name='twomonth',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
