# Generated by Django 3.0.14 on 2021-10-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0012_auto_20211014_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceltestdata',
            name='code',
            field=models.CharField(max_length=500),
        ),
    ]
