# Generated by Django 3.0.14 on 2021-10-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0013_auto_20211018_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceltestdata',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='exceltestdata',
            name='onemonth',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exceltestdata',
            name='ssnum',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='exceltestdata',
            name='thmonth',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exceltestdata',
            name='twomonth',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
