# Generated by Django 3.0.14 on 2021-09-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20210930_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='url',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
